---
- name: Testing initial on devstack-admin
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: vm1
       image: Ubuntu-18.04
       timeout: 200
       flavor: d2
       


  
