---
- name: Testing initial on devstack-admin
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: vm1
       image: e294a710-6e6a-45d3-b9cd-4e61880d10ee
       key_name: automation-key
       timeout: 200
       flavor: d2
       auto_ip: no
       network: b9231b7f-fe92-422b-ae6d-0160f097bd44
       security_groups: default
       meta:
         os: ubuntu

  
